FROM python:3.8-slim-buster

RUN apt update -y && apt upgrade -y

RUN useradd --user-group --system --create-home --no-log-init pythonuser

WORKDIR /api

RUN chown -R pythonuser:pythonuser /api \
    && chmod 755 /api

ADD requirements.dev.txt /api
ADD requirements.txt /api

USER pythonuser

RUN python -m pip install -r requirements.dev.txt

CMD python -m pytest --cov && python -m pytest /api/tests